- name: Render candidate configuration
  napalm_config:
    hostname: "{{ inventory_hostname }}"
    template: "{{ config_template }}"
    template_vars: "{{ j2_vars }}"
    replace: true
    timeout: "{{ load_timeout }}"
  register: candidate

- name: Commit candidate configuration
  napalm_config:
    hostname: "{{ inventory_hostname }}"
    commit: true
    timeout: "{{ commit_timeout }}"
  when: candidate.diff is defined

- name: Display configuration diff
  debug:
    msg: "Config diff for {{ inventory_hostname }}:\n{{ candidate.diff }}"
  when: candidate.diff is defined

- name: Roll back on excessive diffs
  include_tasks: rollback.yml
  when: candidate.diff is defined and (candidate.diff.splitlines() | length) > diff_tolerance

