- name: Check LLDP/OSPF adjacency
  napalm_get:
    hostname: "{{ inventory_hostname }}"
    get_lldp_neighbors: true
  register: lldp

- name: Fail if adjacency count is below expected
  fail:
    msg: "Adjacency down on {{ inventory_hostname }}"
  when: lldp.lldp_neighbors | length < expected_neighbors[inventory_hostname]

- name: Ping leaf loopbacks for ECMP test
  raw: |
    ping -c 3 {{ item }}
  loop: "{{ leaf_loopbacks }}"
  register: ping_results

- name: Fail on ping errors
  fail:
    msg: "Ping failed from {{ inventory_hostname }} to {{ item.item }}"
  loop: "{{ ping_results.results }}"
  when: item.rc != 0
